server:
  port: 8080

spring:
  datasource:
    username: skillbox
    password: Skillbox
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
indexing-settings:
  sites:
      - url: https://www.svetlovka.ru
        name: Библиотека им. М.А. Светлова
      - url: https://et-cetera.ru/mobile
        name: Московский театр «Et Cetera»
jsoup:
  user-agent: PrettySearchBot
  referrer: http://www.google.com
  timeout-min: 50
  timeout-max: 150
